version: 1

formatters:
  simple:
    format: "%(asctime)s -- %(levelname)s -- %(funcName)s -- %(message)s"
  extended:
    format: "%(asctime)s -- %(name)s::%(levelname)s -- %(funcName)s::%(pathname)s -- %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    filename: reverberationTime.log
    formatter: extended

loggers:
  dev:
    handlers: [console, file_handler]
    propagate: false
  test:
    handlers: [file_handler]
    propagate: false
  production:
    handlers: [console, file_handler]
    propagate: false
root:
  handlers: [file_handler]
  